### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by dotfortun3-code**
Version bump

### CODE REVIEW

**Comment by dotfortun3-code** [comment]
Nevermind, I figured out what I am doing.

**Comment by rcoletti116** [comment]
Are you going to use this Git repo or your own going forward? I have some docs I'd like to contribute; Readme and Wiki. There are probably more ReadMe updates once you get this first API release published. 

I've also been working on Temp Sensor and Filter Indication, but keep running into little issues. Would love to see us crack it.

**Comment by dotfortun3-code** [comment]
I'm going to use the new repo since this one  is marked deprecated. 

I renamed it to homebridge-infinitude-v2 to make it clearer and published the current build to NPM.

Both those features sound great. I have some ideas for other features as well, we can chat about them on Discord or something if you want.

**Comment by rcoletti116** [comment]
Sounds good. I'm rcoletti on the homebridge discord.

**Pull request closed without merging**
